# Generated by Django 4.2.27 on 2025-12-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Não Informado', 'Não Informado')], max_length=20)),
            ],
        ),
    ]
