# Generated by Django 4.2.27 on 2025-12-05 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[(1, 'MORNING'), (2, 'AFTERNOON'), (3, 'EVENING'), (4, 'NIGHT')], max_length=10)),
                ('anamnese', models.TextField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('crm', models.IntegerField()),
                ('especialidade', models.CharField(max_length=50)),
                ('atendimentos', models.ManyToManyField(through='consultas.Atendimento', to='consultas.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='idMedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendente', to='consultas.medico'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='idPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendido', to='consultas.paciente'),
        ),
    ]
